// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://utcgcwhmvmoifjasuvvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV0Y2djd2htdm1vaWZqYXN1dnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjY1OTcsImV4cCI6MjA2MTQwMjU5N30.MNZSrVMYTZj3IFDM1l32MXZKTD7DdHchY28dPzTlro0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);